---
collections:
- name: https://github.com/OneIdentity/ansible-privilege-manager/releases/download/v0.1.0/oneidentity-privilege_manager-0.1.0.tar.gz
- name: https://github.com/OneIdentity/ansible-authentication-services/releases/download/v0.3.1/oneidentity-authentication_services-0.3.1.tar.gz
