---
collections:
- name: https://github.com/OneIdentity/ansible-privilege-manager/releases/download/v0.1.0/oneidentity-privilege_manager-0.1.0.tar.gz
- name: https://github.com/OneIdentity/ansible-authenticationservices/releases/download/v0.0.8/oneidentity-authentication_services0.0.8.tar.gz
