---
- hosts: all
  gather_facts: false

  vars:
    # Join
    join_server: 192.168.92.162

    # Preflight
    preflight_mode: sudo
    preflight_verbose: false
    preflight_extra_args: ''

    # Directories
    software_dir: "/var/lib/awx/projects/7.3.0.2"
    software_tmp_dir: /root/client

    # Facts
    preflight_facts_generate: true
    preflight_facts_verbose: false

    # Reports
    preflight_reports_generate: true
    preflight_reports_backup: false

    # Caminho para o instalador pmpreflight
    pmpreflight_installer: "/var/lib/awx/projects/7.3.0.2/pmpreflight"  # Altere para o caminho correto do instalador pmpreflight

  roles:
    - name: oneidentity.privilege_manager.preflight

  tasks:
    # Gather facts (se necessário)
    - name: Gather host information
      include_tasks: /runner/requirements_collections/ansible_collections/oneidentity/privilege_manager/roles/preflight/tasks/gather_facts.yml

    # Verificar se o diretório do pacote do instalador existe
    - name: Check package directory for preflight installer
      include_tasks: /runner/requirements_collections/ansible_collections/oneidentity/privilege_manager/roles/preflight/tasks/utils/check_package_directory.yml

    # Criar o diretório temporário se necessário
    - name: Create temp directory for installation
      include_tasks: /runner/requirements_collections/ansible_collections/oneidentity/privilege_manager/roles/preflight/tasks/utils/temp_dir_create.yml

    # Copiar o instalador pmpreflight para o diretório de destino
    - name: Copy pmpreflight installer
      copy:
        src: "{{ pmpreflight_installer }}"  # Usando a variável com o caminho correto
        dest: "{{ software_tmp_dir }}/pmpreflight"  # Destino para o arquivo copiado
      when: pmpreflight_installer is defined and pmpreflight_installer != ""

    # Falhar se o instalador não for encontrado
    - name: Fail if installer not found
      fail:
        msg: "Preflight installer not found at {{ pmpreflight_installer }}"
      when: pmpreflight_installer is not defined or pmpreflight_installer == ""

    # Executar tarefas do preflight após a cópia do instalador
    - name: Execute preflight tasks
      include_tasks: /runner/requirements_collections/ansible_collections/oneidentity/privilege_manager/roles/preflight/tasks/preflight_with_copy.yml

    # Gerar relatórios
    - name: Generate preflight reports
      include_tasks: /runner/requirements_collections/ansible_collections/oneidentity/privilege_manager/roles/preflight/tasks/generate_reports.yml
